
library(CRSSIO)
stopifnot(packageVersion("CRSSIO") >= "0.6.3")
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(feather))
suppressPackageStartupMessages(library(stringr))
library(RWDataPlyr)
stopifnot(packageVersion("RWDataPlyr") >= "0.6.0")
suppressPackageStartupMessages(library(data.table))
library(CoRiverNF)
source('code/plot_nameFunctions.r')
source('code/getScenarioData.R')
source('code/dataTaggingFunctions.R')
source('code/getICPEData.R')
source('code/plottingFunctions.R')
source('code/getCondProbs.R')
source('code/plotFirstYearShortCond.R')
source('code/plotCloudFig.R')
source("code/compute_dcp_probs.R")
source("code/system_condition_heat_map.R")
source("code/crss_res_directory_setup.R")
source("code/specify_ui.R")
source("code/create_cs_csv.R")
source("code/create_dcp_table.R")
source("code/create_ig_sys_table.R")
source("code/create_scenario_comparison_figures.R")
source("code/create_std_ind_figures.R")
source("code/process_all_rdfs.R")
source("code/process_everything.R")
source("code/access_ui_list.R")
source("code/specify_individual_plots.R")
source("code/check_ui_update_defaults.R")

#source("code/november2019_ui.R")

#ui <- specify_ui()
#ui <- nov2019_ui()

source("code/dev_ui.R")
ui <- dev_ui()

process_everything(ui)


